config/routes.rb
Rails.application.routes.draw do
  root to: 'calculations#index'
  resources :calculations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  validate :calculation, :validate_inputs

  after_initialize do
    # Populate the various fields prior to displaying them
    @inputs = InputList.new(Calculation::INPUT_FIELDS)
    @inputs.set_values(self.calculation&.fetch('inputs', nil)&.symbolize_keys)
    @outputs = set_outputs
  end

  # Match input keys to their classes
  # This structure won't play nicely with multiple copies of an input, e.g. for two different people
  # However, it should be possible to support that with minor changes. Or with multiple input names :-(
  INPUT_FIELDS = {
    input_user_age: Input::UserAge,
    input_housing_sector: Input::HousingSector,
    input_owner_eligible: Input::OwnerEligible,
    input_housing_owner_loan: Input::HousingOwnerLoan,
    input_owner_capital: Input::OwnerCapital,
    input_owner_service: Input::OwnerService
  }

  # Match engine logic steps to their classes
  # Not currently used! All connectors are hardcoded. Frankly everything could be hardcoded.
  # PROCESSING_STEPS = {
  #   s2_dwp_owner_eligible: Process::S2DwpOwnerEligible,
  #   s2_dwp_owner_mortgage: Process::S2DwpOwnerMortgage,
  #   s2_dwp_owner_mortgage_limit: Process::S2DwpOwnerMortgageLimit,
  #   s2_dwp_owner_standardinterest: Process::S2DwpOwnerStandardInterest,
  #   s1_pensioner_user: Process::S1PensionerUser
  # }

  # Define output fields and match to classes
  OUTPUT_FIELDS = {
    output_owner_occupier: Output::OwnerOccupier,
    output_owner_interest: Output::OwnerInterest
  }

  def calculation=(input_hash)
    @inputs = InputList.new(INPUT_FIELDS, input_hash)
    @outputs = set_outputs
    super({
      inputs: inputs.serialized,
      outputs: serialize_outputs
    })
  end

  def self.permitted_inputs
    INPUT_FIELDS.keys
  end

  def inputs
    @inputs ||= InputList.new(INPUT_FIELDS)
  end

  def validate_inputs
    inputs.add_validation_errors(errors)
  end

  def set_outputs
    OUTPUT_FIELDS.map do |output, klass|
      klass.new(inputs)
    end
  end

  def serialize_outputs
    @outputs.map{|output| output.as_json}.inject(:merge)
  end
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: [:show, :edit, :update, :destroy]

  # GET /calculations
  # GET /calculations.json
  def index
    @calculations = Calculation.all
  end

  # GET /calculations/1
  # GET /calculations/1.json
  def show
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  # GET /calculations/1/edit
  def edit
  end

  # POST /calculations
  # POST /calculations.json
  def create
    @calculation = Calculation.new(calculation_params)

    respond_to do |format|
      if @calculation.save
        format.html { redirect_to @calculation, notice: 'Calculation was successfully created.' }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1
  # PATCH/PUT /calculations/1.json
  def update
    respond_to do |format|
      if @calculation.update(calculation_params)
        format.html { redirect_to @calculation, notice: 'Calculation was successfully updated.' }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1
  # DELETE /calculations/1.json
  def destroy
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to calculations_url, notice: 'Calculation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculation_params
      params.require(:calculation).permit(calculation: permitted_inputs)
    end

    def permitted_inputs
      Calculation.permitted_inputs
    end
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/_currency.html.erb
<%= form.number_field "calculation[#{input.first}]", value: input.last.value, min: 0 %>

app/views/calculations/_date.html.erb
<%= form.date_field "calculation[#{input.first}]", value: input.last.value %>

app/views/calculations/_form.html.erb
<%= form_with(model: calculation, local: true) do |form| %>
  <% if calculation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calculation.errors.count, "error") %> prohibited this calculation from being saved:</h2>

      <ul>
      <% calculation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% calculation.inputs.list.each do |input| %>
    <div class="field">
      <%= form.label input.last.label %>
      <%= render :partial => "#{input.last.type}", :locals=>{form: form, input: input} %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calculations/_radio.html.erb
<% input.last.options.each do |option| %>
  <%= form.radio_button "calculation[#{input.first}]", option, checked: option == input.last.value %>
  <%= form.label "calculation[#{input.first}]_#{option}", option %>
<% end %>

app/views/calculations/edit.html.erb
<h1>Editing Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Show', @calculation %> |
<%= link_to 'Back', calculations_path %>

app/views/calculations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calculations</h1>

<table>
  <thead>
    <tr>
      <th>Calculation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calculations.each do |calculation| %>
      <tr>
        <td><%= calculation.calculation %></td>
        <td><%= link_to 'Show', calculation %></td>
        <td><%= link_to 'Edit', edit_calculation_path(calculation) %></td>
        <td><%= link_to 'Destroy', calculation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calculation', new_calculation_path %>

app/views/calculations/new.html.erb
<h1>New Calculation</h1>

<%= render 'form', calculation: @calculation %>

<%= link_to 'Back', calculations_path %>

app/views/calculations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calculation:</strong>
  <%= @calculation.calculation %>
</p>

<%= link_to 'Edit', edit_calculation_path(@calculation) %> |
<%= link_to 'Back', calculations_path %>